
SYSTEM_ROLE_CONTENT = """请总结这篇文档总结学校的性质、办学层次、办学地点、是否是示范、是否是骨干、是否是卓越、是否是楚怡高水平学校、优势专业.只要不明确表示本校是示范校,骨干校,卓越校,楚怡高水平学校,均不算是说明本校是对应荣誉称号学校,比如其中有全国优秀教师、省职业教育“楚怡”教师教学创新团队及省“楚怡”教学名师等骨干力量不能说明本校是楚怡高水平学校!
输出结果格式为一个标准的json组成的List 格式为[{"学校名称":XXXX,"学校性质":公办/民办/未提及,"办学层次":高职(专科)/本科,"办学地点":[xxx,xxx],"示范性院校":是/未提及,"骨干院校":是/未提及,"卓越院校":是/未提及,"楚怡高水平院校":A档/B档/是-档位未知/未提及,"优势专业":[{"专业名称":XXXX,"原因":xxxxx}]}],举例用户输入为湖南化工职业技术学院,长沙幼儿师范高等专科学校,湘中幼儿师范高等专科学校 则输出结果为
[{"学校名称":"湖南化工职业技术学院","学校性质":"公办","办学层次":"高职(专科)","办学地点":["株洲"],示范性院校":"是","骨干院校":"未提及","卓越院校":"是","楚怡高水平院校":"A档","优势专业":[]},
{"学校名称":"长沙幼儿师范高等专科学校","学校性质":"公办","办学层次":"高职(专科)","办学地点":["长沙"],"示范性院校":"未提及","骨干院校":"未提及","卓越院校":"未提及","楚怡高水平院校":"是-档位未知","优势专业":[{"专业名称":"学前教育专业群","原因":"入选湖南省楚怡高职高水平专业群"},{"专业名称":"数字媒体技术专业群","原因":"入选湖南省楚怡高职高水平专业群"}]},
{"学校名称":"湘中幼儿师范高等专科学校","学校性质":"公办","办学层次":"高职(专科)","办学地点":["邵阳"],"示范性院校":"未提及","骨干院校":"未提及","卓越院校":"未提及","楚怡高水平院校":"未提及","优势专业":[]}
],根据用户输入的关键词或者关键词组,按照格式输出判定结果.
"""

KEYWORDS_FILE_NAME = './data/keywords.txt'
UPLOAD_DIR = '$/DOCX/' #.表示相对路径 $表示从根路径开始找
STREAM = true
MODEL_ID = 'ep-20250208112736-r5hxt'
LOCAL_RSP_FILE_PATH = '$/data/region_local.txt'
FAIL_RSP_FILE_PATH = '$/data/region_fail.txt'
AI_MODEL = 'DEEPSEEK_R1'
MAX_CONCURRENT_TASKS = 100
BATCH_SIZE = 100 